import { PublicKey } from '@solana/web3.js'

export default {
  id: new PublicKey('GTg2JHaaTyz7DXknwCNVPSMPLognrqXUm6uoHA3j1JRb'),
  baseMint: new PublicKey('HJbNXx2YMRxgfUJ6K4qeWtjatMK5KYQT1QnsCdDWywNv'),
  quoteMint: new PublicKey('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'),
  lpMint: new PublicKey('GTy3TKmh3Ejrdh7iTALUG3PYv4VC7wgwM9vGgdLj6Rus'),
  version: 4,
  programId: new PublicKey('675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8'),
  authority: new PublicKey('5Q544fKrFoe6tsEbD7S8EmxGTJYAKtTVhAW5Q5pge4j1'),
  openOrders: new PublicKey('3atg3g6TkshhS9fsnBf9hArsHCYyUQG9fdPLC5SNzgEW'),
  targetOrders: new PublicKey('CJ6X2FuFbDbADzZuAiTbtRsfh8j7EZzcFnMXEndnceqS'),
  baseVault: new PublicKey('BA6pvLDkEipsxWTQTFTL76Npozy8KGmPwWBzQ4hyPxrx'),
  quoteVault: new PublicKey('4kUo3sQMRjVwbyxPtVS4hgANXpCvXEtKVhdgijyhXv98'),
  withdrawQueue: new PublicKey('ArSS9E1SiMabe4FJAcX35PN3B3Y1seVQed5yir8iFnYM'),
  lpVault: new PublicKey('HmoYM5H5zTgh5WBPmnXen1GkESvNMEPLgE7ZUbxP1MuX'),
  marketVersion: 3,
  marketProgramId: new PublicKey('9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin'),
  marketId: new PublicKey('6NvErACd7kKz5uPDAfXKahW9sFooUJvtfRh5Kzq6GH9z'),
  marketAuthority: new PublicKey('HydTyLGBPmkhxhTENw1B1FEtYYccqF1SWfHa8AEkKxRh'),
  marketBaseVault: new PublicKey('4zEPqVMTPqtGXB8ciRvdrLPEAwr4RaV3ZECuptqMxYbf'),
  marketQuoteVault: new PublicKey('ASZPLhbA2aH6Lqjt94vbeUEQtcj17oX9tKVU7wRSiyDt'),
  marketBids: new PublicKey('26X4cVMDaLtjBZCB61zvWfUUhBKuJxLypR3q6KxWisXD'),
  marketAsks: new PublicKey('DasuF3LWfqooCqTnBhUKMLb5MdUbBg9sXqCDKcXksTXN'),
  marketEventQueue: new PublicKey('D96hP36dLrTshHQb6hEcrNvhpAHeLhNxxk3tjqNSfAcG'),
}
